apiVersion: v1
kind: Template
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      source:
        git:
          uri: https://github.com/King-Of-The-Cookies/deploy_elasticsearch.git
      output:
        to:
          kind: ImageStreamTag
          name: elasticsearch:1
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
