apiVersion: v1
kind: Template
metadata:
  name: elasticsearch-deploy
  labels:
    app: elasticsearch
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      strategy:
        type: Recreate

      replicas: 1
      template:
        metadata:
          name: elasticsearch
          labels:
            app: elasticsearch
            role: elasticsearch
        spec:
          containers:
            - name: elasticsearch
              image: 172.30.1.1:5000/test/elasticsearch:1
              ports:
              - containerPort: 9200
                name: rest
                protocol: TCP
              - containerPort: 9300
                name: inter-node
                protocol: TCP
              env:
              - name: discovery.type
                value: "single-node"
              - name: ES_JAVA_OPTS
                value: "-Xms512m -Xmx512m"
              volumeMounts:
                - name: data
                  mountPath: /usr/share/elasticsearch/data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: "data"
  - apiVersion: v1
    kind: Service
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      ports:
        - name: rest
          port: 9200
          targetPort: 9200
          protocol: TCP
        - name: inter-node
          port: 9300
          targetPort: 9300
          protocol: TCP
      selector:
        role: elasticsearch
